import Head from 'next/head'
import styles from '@/styles/AcercaDeMi.module.css'
import stylesPost from '@/styles/Post.module.css'
import Footer from './Footer'
import Header from './Header'
import Post from "./Post"
import axios from 'axios'

interface Articulo {
  id: string,
  attributes: {
    tittle: string,
    content: string,
    image: any,
    createdAt: string,
    name: string
  }
}

interface Props {
  posts: Articulo[];
}

export default function Blog({posts}: Props) {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
      </Head>
      <Header />
      <main>
          <div className={`${styles.banner} ${styles.titulo}`}>
              <span className="animate__animated animate__fadeInDown animate__delay-1s">Blog</span>
          </div>
            <div className={stylesPost.contenedorTarjetasPost}>
              {
                posts.map((item) => (
                  <Post 
                  _id={item.id}
                  key={item.id}
                  tittle={item.attributes.tittle}
                  content={item.attributes.content}
                  image={item.attributes.image.data.attributes.url}
                  date={item.attributes.createdAt}
                  name={item.attributes.name}
                  />
                ))
              }
            </div>
      </main>
      <br />
      <hr />
      <Footer />
    </>
  );
}

export async function getServerSideProps() {
  const url = `${process.env.API_URL}/api/blogs?populate=*`;
  const response = await axios.get(url, {
    headers: {
      Autorization: `Bearer ${process.env.STRAPI_KEY}`
    }
  })
  const responseJson = await response.data.data;
  return {
    props: {
      posts: responseJson,
    }
  }
}
