import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/EducacionHabilidades.module.css'
import imagenEducacion from "../img/Education-rafiki.png"
import imagenCodeDevelopment from "../img/Low code development-amico.png"
import imagenCodingAmico from "../img/Coding-amico.png"
import imagenCertificado from "../img/certificate.png"
import imagenCertification from "../img/Certification-amico.png"
import Footer from './Footer'
import Header from './Header'
import { GrMysql } from 'react-icons/gr';

export default function EducacionHabilidadesProfesionales() {
  return (
    <>
      <Head>
        <title>Educación y Habilidades Profesionales</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
      </Head>
      <Header />
      <main>
          <div className={`${styles.banner} ${styles.titulo}`}>
              <span className="animate__animated animate__fadeInDown animate__delay-1s">Educación y Habilidades Profesionales</span>
          </div>
          <div className={styles.containerDoble}>
            <div className={styles.columna1}>
                <div className={styles.encabezado}>
                    <b className="animate__animated animate__bounceIn animate__delay-1s">Formación </b>
                    <b className="animate__animated animate__bounceIn animate__delay-1s">Academica</b>
                </div>
                <div className={styles.texto}>
                    <p className="animate__animated animate__zoomIn animate__delay-1s">Enero 2019 -  Enero 2023</p>
                    <p className="animate__animated animate__zoomIn animate__delay-1s">Licenciatura en Ingeniería en Informática y Sistemas</p>
                    <p className="animate__animated animate__zoomIn animate__delay-1s">IX Semestre - Universidad Rafael Landívar</p>
                </div>
                <div className={styles.texto}>
                    <p className="animate__animated animate__zoomIn animate__delay-1s">Enero 2017 -  Octubre 2018</p>
                    <p className="animate__animated animate__zoomIn animate__delay-1s">Bachillerato en Ciencias y Letras</p>
                    <p className="animate__animated animate__zoomIn animate__delay-1s">Egresado - Colegio Dr. Rodolfo Robles</p>
                </div>
            </div>
            <div className={styles.columna2}>
                <Image src={imagenEducacion} alt="Imagen Educacion" width={300} height={300} className={styles.ilustracion}/>
            </div>
          </div>
          
        <div className={styles.containerDobleSegundo}>
            <div className={styles.columnaNo1}>
                <div className={styles.graficas}>
                    <Image src={imagenCodeDevelopment} alt="Imagen Educacion" width={500} height={800} className={styles.ilustracionContainer}/>
                    <Image src={imagenCodingAmico} alt="Imagen Educacion" width={500} height={800} className={styles.ilustracionContainer}/>
                </div>
            </div>
            <div className={styles.columnaNo2}>
                <div className={styles.encabezado}>
                    <b className="animate__animated animate__bounceIn animate__delay-1s">Conocimientos, </b>
                    <b className="animate__animated animate__bounceIn animate__delay-1s">habilidades </b>
                    <b className="animate__animated animate__bounceIn animate__delay-1s">e intereses</b>
                </div>
                <p className="animate__animated animate__zoomIn animate__delay-1s">En mi formación estudiantil he aprendido a utilizar las siguientes tecnologías:</p>
                <div className={styles.lenguajes}>
                    <div className={styles.lenguaje}>
                        <p> Java </p> 
                        <svg xmlns="http://www.w3.org/2000/svg" width="144" height="144" viewBox="0 0 24 24">
                            <path d="M9.37 17.51c-3.09.86 1.87 2.64 5.8 1a7.18 7.18 0 0 1-1.1-.54 11.59 11.59 0 0 1-4.16.18c-1.31-.15-.54-.64-.54-.64zm5.33-1.68a16.27 16.27 0 0 1-5.36.26c-1.31-.14-.45-.77-.45-.77-3.4 1.12 1.89 2.4 6.64 1a2.25 2.25 0 0 1-.83-.49zm1.82-9.73s-6.87 1.71-3.59 5.49a1.47 1.47 0 0 1-.25 2.12s2.46-1.27 1.33-2.86-1.86-2.22 2.51-4.75z">
                            </path>
                            <path d="M18.13 19.14s.56.46-.63.82c-2.27.69-9.43.9-11.42 0-.72-.31.62-.74 1-.83a2.54 2.54 0 0 1 .69-.08c-.8-.56-5.15 1.1-2.21 1.58 8.05 1.37 14.64-.56 12.57-1.49zm-2.76-4.88a7 7 0 0 1 .92-.49s-1.51.27-3 .4a28.11 28.11 0 0 1-4.82.05C6.09 13.91 9.74 13 9.74 13a6.81 6.81 0 0 0-3.16.75c-2.06 1.03 5.09 1.48 8.79.51zm.91 2.44a.39.39 0 0 1-.08.09c5-1.32 3.18-4.65.78-3.81a.71.71 0 0 0-.33.25s.14-.05.43-.12c1.22-.25 2.92 1.63-.8 3.59zM12 13c-.74-1.67-3.26-3.14 0-5.71C16.09 4.08 14 2 14 2c.84 3.31-3 4.31-4.34 6.37-.93 1.41.47 2.92 2.34 4.63z"></path><path d="M16.41 21.32a29.75 29.75 0 0 1-9.14.14s.46.38 2.84.53c3.61.23 9.15-.12 9.29-1.83 0 0-.26.64-2.99 1.16z">
                            </path>
                        </svg>
                    </div>
                    <div className={styles.lenguaje}>
                        <p>Python</p>
                        <svg xmlns="http://www.w3.org/2000/svg" width="144" height="144" viewBox="0 0 24 24">
                            <path d="M9.585 11.692h4.328s2.432.039 2.432-2.35V5.391S16.714 3 11.936 3C7.362 3 7.647 4.983 7.647 4.983l.006 2.055h4.363v.617H5.92s-2.927-.332-2.927 4.282 2.555 4.45 2.555 4.45h1.524v-2.141s-.083-2.554 2.513-2.554zm-.056-5.74a.784.784 0 1 1 0-1.57.784.784 0 1 1 0 1.57z">
                            </path>
                            <path d="M18.452 7.532h-1.524v2.141s.083 2.554-2.513 2.554h-4.328s-2.432-.04-2.432 2.35v3.951s-.369 2.391 4.409 2.391c4.573 0 4.288-1.983 4.288-1.983l-.006-2.054h-4.363v-.617h6.097s2.927.332 2.927-4.282-2.555-4.451-2.555-4.451zm-3.981 10.436a.784.784 0 1 1 0 1.57.784.784 0 1 1 0-1.57z">
                            </path>
                        </svg>
                    </div>
                    <div className={styles.lenguaje}>
                        <p>C++</p>
                        <svg xmlns="http://www.w3.org/2000/svg" width="144" height="144" viewBox="0 0 24 24"><path d="M20.66 7a1.51 1.51 0 0 0-.55-.57l-7.34-4.24a1.67 1.67 0 0 0-1.54 0L3.89 6.43a1.68 1.68 0 0 0-.77 1.33v8.48a1.57 1.57 0 0 0 .22.76 1.51 1.51 0 0 0 .55.57l7.34 4.24a1.67 1.67 0 0 0 1.54 0l7.34-4.24a1.51 1.51 0 0 0 .55-.57 1.57 1.57 0 0 0 .22-.76V7.76a1.57 1.57 0 0 0-.22-.76zM12 17.92A5.92 5.92 0 1 1 17.13 9L16 9.71l-.36.2-1 .61A3 3 0 0 0 9 12a2.88 2.88 0 0 0 .4 1.48 3 3 0 0 0 5.13 0l2.6 1.52A5.94 5.94 0 0 1 12 17.92zm5.92-5.59h-.66V13h-.65v-.66H16v-.66h.66V11h.65v.66h.66zm2.47 0h-.66V13h-.66v-.66h-.65v-.66h.65V11h.66v.66h.66z"></path></svg>
                    </div>
                    <div className={styles.lenguaje}>
                        <p>React</p>
                        <svg xmlns="http://www.w3.org/2000/svg" width="144" height="144" viewBox="0 0 24 24"><circle cx="12" cy="11.245" r="1.785"></circle><path d="m7.002 14.794-.395-.101c-2.934-.741-4.617-2.001-4.617-3.452 0-1.452 1.684-2.711 4.617-3.452l.395-.1.111.391a19.507 19.507 0 0 0 1.136 2.983l.085.178-.085.178c-.46.963-.841 1.961-1.136 2.985l-.111.39zm-.577-6.095c-2.229.628-3.598 1.586-3.598 2.542 0 .954 1.368 1.913 3.598 2.54.273-.868.603-1.717.985-2.54a20.356 20.356 0 0 1-.985-2.542zm10.572 6.095-.11-.392a19.628 19.628 0 0 0-1.137-2.984l-.085-.177.085-.179c.46-.961.839-1.96 1.137-2.984l.11-.39.395.1c2.935.741 4.617 2 4.617 3.453 0 1.452-1.683 2.711-4.617 3.452l-.395.101zm-.41-3.553c.4.866.733 1.718.987 2.54 2.23-.627 3.599-1.586 3.599-2.54 0-.956-1.368-1.913-3.599-2.542a20.683 20.683 0 0 1-.987 2.542z"></path><path d="m6.419 8.695-.11-.39c-.826-2.908-.576-4.991.687-5.717 1.235-.715 3.222.13 5.303 2.265l.284.292-.284.291a19.718 19.718 0 0 0-2.02 2.474l-.113.162-.196.016a19.646 19.646 0 0 0-3.157.509l-.394.098zm1.582-5.529c-.224 0-.422.049-.589.145-.828.477-.974 2.138-.404 4.38.891-.197 1.79-.338 2.696-.417a21.058 21.058 0 0 1 1.713-2.123c-1.303-1.267-2.533-1.985-3.416-1.985zm7.997 16.984c-1.188 0-2.714-.896-4.298-2.522l-.283-.291.283-.29a19.827 19.827 0 0 0 2.021-2.477l.112-.16.194-.019a19.473 19.473 0 0 0 3.158-.507l.395-.1.111.391c.822 2.906.573 4.992-.688 5.718a1.978 1.978 0 0 1-1.005.257zm-3.415-2.82c1.302 1.267 2.533 1.986 3.415 1.986.225 0 .423-.05.589-.145.829-.478.976-2.142.404-4.384-.89.198-1.79.34-2.698.419a20.526 20.526 0 0 1-1.71 2.124z"></path><path d="m17.58 8.695-.395-.099a19.477 19.477 0 0 0-3.158-.509l-.194-.017-.112-.162A19.551 19.551 0 0 0 11.7 5.434l-.283-.291.283-.29c2.08-2.134 4.066-2.979 5.303-2.265 1.262.727 1.513 2.81.688 5.717l-.111.39zm-3.287-1.421c.954.085 1.858.228 2.698.417.571-2.242.425-3.903-.404-4.381-.824-.477-2.375.253-4.004 1.841.616.67 1.188 1.378 1.71 2.123zM8.001 20.15a1.983 1.983 0 0 1-1.005-.257c-1.263-.726-1.513-2.811-.688-5.718l.108-.391.395.1c.964.243 2.026.414 3.158.507l.194.019.113.16c.604.878 1.28 1.707 2.02 2.477l.284.29-.284.291c-1.583 1.627-3.109 2.522-4.295 2.522zm-.993-5.362c-.57 2.242-.424 3.906.404 4.384.825.47 2.371-.255 4.005-1.842a21.17 21.17 0 0 1-1.713-2.123 20.692 20.692 0 0 1-2.696-.419z"></path><path d="M12 15.313c-.687 0-1.392-.029-2.1-.088l-.196-.017-.113-.162a25.697 25.697 0 0 1-1.126-1.769 26.028 26.028 0 0 1-.971-1.859l-.084-.177.084-.179c.299-.632.622-1.252.971-1.858.347-.596.726-1.192 1.126-1.77l.113-.16.196-.018a25.148 25.148 0 0 1 4.198 0l.194.019.113.16a25.136 25.136 0 0 1 2.1 3.628l.083.179-.083.177a24.742 24.742 0 0 1-2.1 3.628l-.113.162-.194.017c-.706.057-1.412.087-2.098.087zm-1.834-.904c1.235.093 2.433.093 3.667 0a24.469 24.469 0 0 0 1.832-3.168 23.916 23.916 0 0 0-1.832-3.168 23.877 23.877 0 0 0-3.667 0 23.743 23.743 0 0 0-1.832 3.168 24.82 24.82 0 0 0 1.832 3.168z"></path></svg>
                    </div>
                    <div className={styles.lenguaje}>
                        <p>Vue</p>
                        <svg xmlns="http://www.w3.org/2000/svg" width="144" height="144" viewBox="0 0 24 24"><path d="m12 12.765 5.592-9.437h-3.276L12 7.33v.002L9.688 3.328h-3.28z"></path><path d="M18.461 3.332 12 14.235 5.539 3.332H1.992L12 20.672l10.008-17.34z"></path></svg>
                    </div>
                    <div className={styles.lenguaje}>
                        <p>JavaScript</p>
                        <svg xmlns="http://www.w3.org/2000/svg" width="144" height="144" viewBox="0 0 24 24"><path d="M3 3h18v18H3V3zm16.525 13.707c-.131-.821-.666-1.511-2.252-2.155-.552-.259-1.165-.438-1.349-.854-.068-.248-.078-.382-.034-.529.113-.484.687-.629 1.137-.495.293.09.563.315.732.676.775-.507.775-.507 1.316-.844-.203-.314-.304-.451-.439-.586-.473-.528-1.103-.798-2.126-.775l-.528.067c-.507.124-.991.395-1.283.754-.855.968-.608 2.655.427 3.354 1.023.765 2.521.933 2.712 1.653.18.878-.652 1.159-1.475 1.058-.607-.136-.945-.439-1.316-1.002l-1.372.788c.157.359.337.517.607.832 1.305 1.316 4.568 1.249 5.153-.754.021-.067.18-.528.056-1.237l.034.049zm-6.737-5.434h-1.686c0 1.453-.007 2.898-.007 4.354 0 .924.047 1.772-.104 2.033-.247.517-.886.451-1.175.359-.297-.146-.448-.349-.623-.641-.047-.078-.082-.146-.095-.146l-1.368.844c.229.473.563.879.994 1.137.641.383 1.502.507 2.404.305.588-.17 1.095-.519 1.358-1.059.384-.697.302-1.553.299-2.509.008-1.541 0-3.083 0-4.635l.003-.042z"></path></svg>
                    </div>
                    <div className={styles.lenguaje}>
                        <p>TypeScript</p>
                        <svg xmlns="http://www.w3.org/2000/svg" width="144" height="144" viewBox="0 0 24 24"><path d="M19.24 3H4.76A1.76 1.76 0 0 0 3 4.76v14.48A1.76 1.76 0 0 0 4.76 21h14.48A1.76 1.76 0 0 0 21 19.24V4.76A1.76 1.76 0 0 0 19.24 3zm-5.8 10h-2.25v6.44H9.4V13H7.15v-1.46h6.29zm5.8 5.28a1.71 1.71 0 0 1-.67.74 3 3 0 0 1-1 .39 5.81 5.81 0 0 1-1.2.12 7 7 0 0 1-1.23-.11 4.52 4.52 0 0 1-1-.33v-1.71l-.06-.06h.06v.07a3.41 3.41 0 0 0 1 .54 3.06 3.06 0 0 0 1.13.2 2.58 2.58 0 0 0 .6-.06 1.47 1.47 0 0 0 .42-.17.75.75 0 0 0 .25-.25.69.69 0 0 0-.06-.74 1.24 1.24 0 0 0-.35-.33 3.12 3.12 0 0 0-.53-.3l-.67-.28a3.57 3.57 0 0 1-1.37-1 2 2 0 0 1-.46-1.33 2.16 2.16 0 0 1 .24-1.06 2.09 2.09 0 0 1 .66-.71 2.88 2.88 0 0 1 1-.42 5.11 5.11 0 0 1 1.19-.13 7 7 0 0 1 1.09.07 4.53 4.53 0 0 1 .88.23v1.65a2.42 2.42 0 0 0-.42-.24 3.58 3.58 0 0 0-.49-.17 3 3 0 0 0-.49-.1 2.45 2.45 0 0 0-.46 0 2.29 2.29 0 0 0-.56.06 1.54 1.54 0 0 0-.43.16.78.78 0 0 0-.26.25.63.63 0 0 0-.09.33.62.62 0 0 0 .1.35 1.19 1.19 0 0 0 .3.29 2.15 2.15 0 0 0 .46.28l.63.28a6.56 6.56 0 0 1 .84.42 2.65 2.65 0 0 1 .64.49 1.79 1.79 0 0 1 .42.63 2.48 2.48 0 0 1 .14.85 2.68 2.68 0 0 1-.25 1.08z"></path></svg>
                    </div>
                    <div className={styles.lenguaje}>
                        <p>Firebase</p>
                        <svg xmlns="http://www.w3.org/2000/svg" width="144" height="144" viewBox="0 0 24 24"><path d="M5.239 15.063 7.21 2.381a.453.453 0 0 1 .847-.145l2.12 3.979-4.938 8.848zM19.24 18.14 17.363 6.469a.454.454 0 0 0-.766-.246L4.76 18.14l6.55 3.691c.411.23.912.23 1.323 0l6.607-3.691zM13.917 7.955 12.4 5.052a.452.452 0 0 0-.8 0L4.939 16.989l8.978-9.034z"></path></svg>
                    </div>
                    <div className={styles.lenguaje}>
                        <p>Html</p>
                        <svg xmlns="http://www.w3.org/2000/svg" width="144" height="144" viewBox="0 0 24 24"><path d="M4.136 3.012h15.729l-1.431 16.15-6.451 1.826-6.414-1.826-1.433-16.15zm5.266 7.302-.173-2.035 7.533.002.173-1.963-9.87-.002.522 5.998h6.835l-.243 2.566-2.179.602-2.214-.605-.141-1.58H7.691l.247 3.123L12 17.506l4.028-1.08.558-6.111H9.402v-.001z"></path></svg>
                    </div>
                    <div className={styles.lenguaje}>
                        <p>Css</p>
                        <svg xmlns="http://www.w3.org/2000/svg" width="144" height="144" viewBox="0 0 24 24"><path d="M4.192 3.143h15.615l-1.42 16.034-6.404 1.812-6.369-1.813L4.192 3.143zM16.9 6.424l-9.8-.002.158 1.949 7.529.002-.189 2.02H9.66l.179 1.913h4.597l-.272 2.62-2.164.598-2.197-.603-.141-1.569h-1.94l.216 2.867L12 17.484l3.995-1.137.905-9.923z"></path></svg>
                    </div>
                    <div className={styles.lenguaje}>
                        <p>Figma</p>
                        <svg xmlns="http://www.w3.org/2000/svg" width="144" height="144" viewBox="0 0 24 24"><path d="M15.332 8.668a3.333 3.333 0 0 0 0-6.663H8.668a3.333 3.333 0 0 0 0 6.663 3.333 3.333 0 0 0 0 6.665 3.333 3.333 0 0 0 0 6.664A3.334 3.334 0 0 0 12 18.664V8.668h3.332z"></path><circle cx="15.332" cy="12" r="3.332"></circle></svg>
                    </div>
                </div>
                <div className={styles.texto}>
                    <p className="animate__animated animate__zoomIn animate__delay-1s">Como gestores de base de datos que he aprendido a usar se encuentran:</p>
                </div>
                <div className={styles.lenguajes}>
                    <div className={styles.lenguaje}>
                        <p>MongoDB</p>
                        <svg xmlns="http://www.w3.org/2000/svg" width="144" height="144" viewBox="0 0 24 24"><path d="M13.74 4.23c-.84-1-1.57-2-1.71-2.22H12c-.14.21-.87 1.22-1.71 2.22-7.2 9.19 1.14 15.39 1.14 15.39l.07.05c.06.95.22 2.33.22 2.33h.62s.15-1.37.21-2.33l.07-.06s8.32-6.19 1.12-15.38zM12 19.48a3.48 3.48 0 0 1-.48-.48L12 9l.45 10a3.57 3.57 0 0 1-.45.48z"></path></svg>
                    </div>
                    <div className={styles.lenguaje}>
                        <p>MySQL</p>
                        <GrMysql />
                    </div>
                </div>
                <div className={styles.texto}>
                    <p className="animate__animated animate__zoomIn animate__delay-1s">Áreas con las que más me identifico respecto a mi formación académica son:
                    </p>
                    <ul>
                        <li className="animate__animated animate__zoomIn animate__delay-1s">Trabajo con bases de datos no relacionales.</li>
                        <li className="animate__animated animate__zoomIn animate__delay-1s">Creación de vistas para frontend.</li>
                        <li className="animate__animated animate__zoomIn animate__delay-1s">Trabajo con algoritmos en el área de backend.</li>
                        <li className="animate__animated animate__zoomIn animate__delay-1s">Generación de documentación.</li>
                    </ul>
                </div>
            </div>
        </div>
        <div className={styles.containerDobleTercero}>
             <div className={styles.letras}>
                <div className={styles.encabezado}>
                    <b className="animate__animated animate__bounceIn animate__delay-1s">Formacion </b>
                    <b className="animate__animated animate__bounceIn animate__delay-1s">Fuera del Aula</b>
                </div>
                <p className="animate__animated animate__zoomIn animate__delay-1s">
                    He aprendido los fundamentos de programación en Javascript 
                    por medio de Grasshopper, la cual es una app de programación 
                    para principiantes. 
                </p>
                <Image src={imagenCertification} alt="Imagen Educacion" width={300} height={300} className={styles.ilustracion}/>
            </div>
            <div className={styles.imagenes}>
                <Image src={imagenCertificado} alt="Imagen Educacion" width={300} height={500} className={styles.ilustracionCertificado}/>
            </div>
        </div>
      </main>
      <br />
      <hr />
      <Footer />
    </>
  );
}