import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/ProyectosRecientes.module.css'
import imagen from "../img/Software code testing-amico.png"
import imagenProyecto1 from "../img/SimuladorControlDeProcesos.png"
import imagenProyecto2 from "../img/Yotube.png"
import imagenProyecto3 from "../img/Videojuego.png"
import Footer from './Footer'
import Header from './Header'
import Link from "next/link"

export default function ProyectosRecientes() {
  return (
    <>
      <Head>
        <title>Proyectos Recientes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
      </Head>
      <Header />
      <main>
        <div className={`${styles.banner} ${styles.titulo}`}>
              <span className="animate__animated animate__fadeInDown animate__delay-1s">Proyectos Recientes</span>
        </div>
        <div className={styles.contenedorDoble}>
            <div className={styles.introduccion}>
                <span className="animate__animated animate__flipInX animate__delay-1s">
                    En el área del desarrollo junto a mi grupo de
                    trabajo, he creado algunas aplicaciones 
                    como las que se mencionan seguidamente,
                    y que son una manera de representar mi
                    trabajo.
                </span>
            </div>
            <Image src={imagen} alt="Imagen 1" width={300} height={300} className={styles.ilustracionPrincipal}/>
        </div>
        <div className={styles.proyectos}>
            <div className={styles.tarjeta}>
                <Image src={imagenProyecto1} alt="Imagen Proyecto No. 1" width={300} height={300} className={styles.ilustracion}/>
                <div className={styles.informacion}>
                    <h1 className={styles.tituloTarjeta}>Simulador de Control de Procesos</h1>
                    <div className={styles.parrafo}>
                        <b>Descripción del proyecto </b>
                        <br />
                        <br />
                        Demostración gráfica del flujo de procesos en memoria
                        principal de una computadora.
                    </div>
                    <div className={styles.parrafo}>
                        <br />
                        <b>Mi rol en el Proyecto</b> 
                        <br />
                        <br />
                        En este proyecto mis responsabilidades fueron; agregar la interfaz base, 
                        sobre la misma en la demostración del flujo de los procesos fui la encargada
                        de las etiquetas, barra de recorrido y espacio de sistema operativo. 
                        <br />
                        <br />
                        Debido a que se trabajaba con multihilos agregué el hilo del tiempo, realice la 
                        implementación de la eliminación de procesos por medio de su ID, 
                        registro en historial de creación y finalización de procesos.
                    </div>
                    <div className={styles.parrafo}>
                        <br />
                        <b>Impacto o Resultado</b>
                        <br />
                        <br />
                        La creación de este programa generó una visión clara sobre el funcionamiento de 
                        la memoria principal de una computadora respecto a la ejecución de procesos. 
                        <br />
                        <br />
                        El resultado obtenido, sobre todo en el área visual del proyecto fue satisfactorio, 
                        pues se notó que aún con no contar con librerías que facilitaran este proceso, se
                        logró entregar una interfaz agradable a la vista.
                    </div>
                    <div className={styles.parrafo}>
                        <br />
                        <b>Proceso de Creación</b>
                        <br />
                        <br />
                        Para la generación de este proyecto primero se estableció la interfaz base para la
                        demostración gráfica de la generación y flujo de procesos en la memoria principal, 
                        ya que se trabajó con multihilos se generaron los hilos correspondientes.
                        <br />
                        <br /> 
                        Seguidamente se generó la clase para contener todos los atributos y métodos
                        correspondientes a un proceso, tales como su creación, eliminación y registro en
                        historial. 
                        <br />
                        <br />
                        Seguidamente se creó la clase del activador encargada de realizar los cambios en la
                        etiqueta cuando se alterna entre procesos. Además se mostró el proceso en ejecución
                        y se implementó la demostración gráfica del recorrido en la ejecución de los procesos.
                        <br />
                        <br />
                        Debido a que se debía controlar si los procesos generados eran soportados dentro de la 
                        memoria principal o excedían el espacio disponible, se controló ese aspecto y se generó 
                        el mensaje de error correspondiente en caso de exceder el espacio disponible.
                    </div>
                    <div className={styles.parrafo}>
                        <Link href="https://github.com/BryanBac/Simulador_Control_de_Procesos">
                                <b>
                                    Link del Repositorio
                                </b>
                        </Link>
                    </div>   
                    <br />
                    <br />
                </div>
            </div>
            <div className={styles.tarjeta}>
                <Image src={imagenProyecto2} alt="Imagen Proyecto No. 2" width={300} height={300} className={styles.ilustracion}/>
                <div className={styles.informacion}>
                    <h1 className={styles.tituloTarjeta}>Youtube</h1>
                    <div className={styles.parrafo}>
                        <b>Descripción del proyecto </b>
                        <br />
                        <br />
                        Recolección y análisis de datos provenientes de 9
                        canales de Youtube.
                    </div>
                    <div className={styles.parrafo}>
                        <br />
                        <b>Mi rol en el Proyecto</b> 
                        <br />
                        <br />
                        Debido a que se debían almacenar los datos en 2 diferentes bases de datos (una
                        base de datos relacional y una base de datos no relacional), fui la encargada 
                        del almacenamiento de datos en la base de datos relacional y del análisis de los 
                        datos provenientes de la misma fuente utilizando el lenguaje de programación R.
                    </div>
                    <div className={styles.parrafo}>
                        <br />
                        <b>Impacto o Resultado</b>
                        <br />
                        <br />
                        El resultado de este proyecto dió las bases sobre cómo es trabajar con bases de datos 
                        de un gran volumen y generó una vista concreta sobre la importancia de realizar un 
                        buen diseño de una base de datos desde un inicio, pues en al principio del proceso 
                        se tuvo que rediseñar parte de la base de datos relacional para asegurar la integridad 
                        de los datos.
                    </div>
                    <div className={styles.parrafo}>
                        <br />
                        <b>Proceso de Creación</b>
                        <br /><br />
                        Primero se busco un tema sobre el cuál recolectar data masiva, ya teniendo el 
                        tema de Youtube en mente se busco la manera de descargar información sobre esta 
                        aplicación con una api de google. Por lo que cada integrante generó la cantidad 
                        de apis correspondientes en su cuenta y se procedió a probar la obtención de los 
                        datos.
                        <br />
                        <br />
                        Luego se generaron las bases de datos correspondientes en mysql y mongodb, para 
                        lo que se generó un script para programar en las computadoras la recolección de datos 
                        automaticamente en cierto horario, proceso que duró un mes, durante el cuál se generaron 
                        las consultas a realizar sobre la data en ambas bases de datos. Para mostrar cómo en ambas 
                        se obtenía la misma información aún con un lenguaje diferente.
                        <br />
                        <br />
                        En el tratamiento de datos con R, se generó el programa de Python que
                        trataba los datos usando una librería de R desde este lenguaje de programación y
                        para el tratamiento de datos directamente desde R se consultaban los datos y se
                        realizaron gráficas comparativas de la tendencia de cada canal, así como la
                        comparativa entre todos.
                    </div>
                    <div className={styles.parrafo}>
                        <div className={styles.enlace}>
                            <Link href="https://github.com/BryanBac/Youtube_web_scaping">
                                <b>
                                    Link del Repositorio No. 1 (Obtención de Datos)
                                </b>
                            </Link>
                        </div>
                        <div className={styles.enlace}>
                            <Link href="https://github.com/BryanBac/Youtube_R">
                                <b>
                                Link del Repositorio No. 2 (Tratamiento de datos)
                                </b>
                            </Link>
                        </div>
                    </div>
                    <br />
                    <br />
                </div>
            </div>
            <div className={styles.tarjeta}>
                <Image src={imagenProyecto3} alt="Imagen Proyecto No. 3" width={300} height={300} className={styles.ilustracion}/>
                <div className={styles.informacion}>
                    <h1 className={styles.tituloTarjeta}>Videojuego</h1>
                    <div className={styles.parrafo}>
                        <b>Descripción del proyecto </b>
                        <br /><br />
                        Realización de un videojuego de peleas utilizando Python.
                    </div>
                    <div className={styles.parrafo}>
                        <br />
                        <b>Mi rol en el Proyecto</b> 
                        <br /><br />
                        Mis tareas en este proyecto fueron la selección de
                        personajes, control de colisiones entre cambio de pantallas, control del diagrama
                        de clases en el que se basa el videojuego, ordenamiento de clases de personajes
                        y agregación de ítems a los personajes.
                    </div>
                    <div className={styles.parrafo}>
                        <br />
                        <b>Impacto o Resultado</b>
                        <br /><br />
                        Crear este videojuego dio una vista sobre cómo un proceso
                        ordenado y la generación de un diagrama previo a la codificación de un programa
                        son de gran utilidad, pues repercute en que aún cuando se trabaje con
                        herramientas nuevas se pueda entregar un producto completo, presentable y a
                        tiempo.
                    </div>
                    <div className={styles.parrafo}>
                        <br />
                        <b>Proceso de Creación</b>
                        <br /><br />
                        Primero se hizo una lluvia de ideas entre los integrantes del
                        grupo, para trabajar sobre un concepto inicial según las indicaciones del
                        proyecto. Seguidamente se procedió a bocetar una idea base del diagrama de clases 
                        para tener una guía en la programación.
                        <br /><br />
                        Luego se aprendió a usar la herramienta pygame, con nociones y guías básicas de 
                        su funcionamiento, se crearon y ordenaron las clases base de los personajes, 
                        las imágenes de cada uno y los fondos. 
                        <br /><br />
                        Posteriormente se establecieron los modos de juego a producir, con ello las mecánicas
                        necesarias para las pantallas y la selección de personajes en cada caso.
                        <br /><br />
                        Después se gregaron puntos de vida y música al vídeojuego. Además se actulizó 
                        el readme del repositorio con los paquetes utilizados. 
                        <br /><br />
                        En el proceso se fue refinando el diseño del diagrama de clases y este también fue 
                        agregado al repositorio.
    
                    </div>
                    <div className={styles.parrafo}>
                        <div className={styles.enlace}>                           
                            <Link href="https://github.com/BryanBac/Videojuego-RPG">
                                <b>
                                Link del Repositorio
                                </b>
                            </Link>
                        </div>
                    </div>
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                    <br />
                </div>
            </div>
        </div>
       </main>
       <br />
      <hr />
      <Footer />
      </>
  );
}